# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listid', models.CharField(max_length=250)),
                ('listname', models.CharField(max_length=250)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=250)),
                ('taskname', models.CharField(max_length=250)),
                ('taskdesc', models.CharField(max_length=1000)),
                ('tasktype', models.CharField(max_length=250)),
                ('duedate', models.DateField(max_length=250)),
                ('priority', models.IntegerField()),
                ('listid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.List')),
            ],
        ),
    ]
